# Robot Mower Advanced Default Configuration
# This file contains default configuration values for the robot mower system

system:
  # Logging configuration
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_file: "logs/robot_mower.log"
  
  # System behavior
  units: "metric"  # metric or imperial
  timezone: "UTC"
  save_state_interval: 300  # Save state every 5 minutes

hardware:
  # Mower hardware configuration
  mower_width: 0.28  # Width of the mower blade in meters
  wheel_diameter: 0.2  # Wheel diameter in meters
  wheel_base: 0.35  # Distance between wheels in meters
  max_speed: 0.5  # Maximum speed in m/s
  max_turn_rate: 45  # Maximum turn rate in degrees/s
  
  # Motor configuration
  motors:
    left_motor_pins: [17, 18]  # GPIO pins for left motor control
    right_motor_pins: [22, 23]  # GPIO pins for right motor control
    pwm_frequency: 1000  # PWM frequency in Hz
    reverse_left: false  # Reverse left motor direction
    reverse_right: false  # Reverse right motor direction
    
  # Sensor configuration
  sensors:
    ultrasonic:
      trigger_pin: 24
      echo_pin: 25
      timeout: 1.0  # Timeout in seconds
      max_distance: 4.0  # Maximum detection distance in meters
    
    imu:
      i2c_bus: 1
      i2c_address: 0x68
      calibration_samples: 100
      
    rain:
      pin: 27
      threshold: 500
      
    current:
      pin: 0  # ADC pin
      threshold: 2.0  # Overcurrent threshold in amps
      
    voltage:
      pin: 1  # ADC pin
      low_threshold: 10.5  # Low voltage threshold in volts
      
  # Actuator configuration
  actuators:
    mower_motor:
      enable_pin: 12
      speed_pin: 13
      pwm_frequency: 1000  # PWM frequency in Hz
      
    blade_height:
      servo_pin: 16
      min_angle: 0
      max_angle: 180
      default_angle: 90

navigation:
  # Navigation configuration
  mowing_pattern: "adaptive"  # parallel_lines, spiral, perimeter_first, zigzag, adaptive
  line_direction: 0.0  # Direction for parallel lines (degrees, 0 = East, 90 = North)
  path_overlap_percent: 10.0  # Percentage of mower width to overlap
  perimeter_passes: 2  # Number of passes around perimeter
  obstacle_buffer: 0.3  # Buffer distance around obstacles in meters
  dock_approach_distance: 2.0  # Distance to switch to precision docking in meters
  
  # GPS configuration (if equipped)
  gps:
    enabled: false
    serial_port: "/dev/ttyAMA0"
    baud_rate: 9600
    precision_threshold: 2.0  # GPS precision threshold in meters
    
  # Compass configuration
  compass:
    enabled: true
    declination: 0.0  # Magnetic declination for your location
    calibration:
      x_offset: 0
      y_offset: 0
      z_offset: 0

lawn:
  # Lawn and boundary configuration
  boundary:
    # List of coordinates defining the lawn boundary
    # Format: [lat, lon] or [x, y] depending on coordinate system
    coordinates: []
    
  # No-mow zones (obstacles)
  no_mow_zones: []
  
  # Dock location
  dock:
    position: [0, 0]  # [lat, lon] or [x, y]
    orientation: 0  # Degrees, 0 = East, 90 = North
    
  # Manually defined mowing zones
  zones: []

schedule:
  # Mowing schedule
  enabled: true
  max_run_time: 120  # Maximum run time in minutes
  rain_delay: 360  # Delay after rain in minutes
  
  # Scheduled mowing times
  mowing_times:
    - day: "monday"
      start_time: "10:00"
      duration: 60  # minutes
    - day: "thursday"
      start_time: "10:00"
      duration: 60  # minutes

security:
  # Security configuration
  pin_code: "0000"  # Default PIN code for control panel
  auto_lock: true  # Automatically lock control panel
  lock_timeout: 300  # Lock after inactivity (seconds)
  
  # Emergency contacts
  emergency_contacts: []

web:
  # Web interface configuration
  port: 7799
  enable_ssl: false
  ssl_cert: ""
  ssl_key: ""
  username: "admin"
  password: "admin"  # Change this!
  
  # MQTT configuration for external communication
  mqtt:
    enabled: false
    broker: "localhost"
    port: 1883
    username: ""
    password: ""
    topic_prefix: "robot_mower/"
    
  # Remote monitoring
  monitoring:
    enabled: false
    update_interval: 60  # Seconds between status updates
    server_url: ""
    api_key: ""
    
advanced:
  # Advanced configuration options
  development_mode: false
  debug_peripherals: false
  simulation: false
  record_data: false
  data_folder: "data/"
  backup_folder: "backups/"
  max_log_size_mb: 10
  max_log_files: 5
